
name: Terraform Plan

on:
  pull_request:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.m.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4
      - run: |
          git fetch origin main
          git diff --name-only origin/main...HEAD > changed.txt
      - id: m
        run: |
          python3 .github/scripts/generate_matrix.py > matrix.json
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  run:
    needs: generate
    strategy:
      matrix:
        stage: ${{ fromJson(needs.generate.outputs.matrix) }}
    uses: ./.github/workflows/reusable.yml
    with:
      stage: ${{ matrix.stage }}
      action: plan
    secrets: inherit
