
name: Terraform Plan

on:
  pull_request:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.m.outputs.matrix }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get changed files (PR safe)
        run: |
          echo "Base: ${{ github.event.pull_request.base.sha }}"
          echo "Head: ${{ github.sha }}"

          git diff --name-only \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.sha }} > changed.txt || true

      - name: Debug
        run: cat changed.txt || true

      - id: m
        run: |
          python3 .github/scripts/generate_matrix.py > matrix.json
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT